import type { Metadata } from "next";
import {IBM_Plex_Mono} from "next/font/google";
import "./globals.css";

// 配置字体变量

const ibm_Plex_Mono = IBM_Plex_Mono({
subsets:['latin'],
weight:['400','700'],
variable:'--font-ibm-plex-mono',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ibm_Plex_Mono.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
